# -*- coding: utf-8 -*-
"""software

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16a67pmQ-KXRiz6iTVsr-oUwgi1iMiceY
"""

# weather modleling using the quadratic equation
a = 3
b = 4
c = 5
x = 2
y = (a * x**2) + (b * x) + c

print("for the values of ",a,"",b,"",c,"y is:",y)